apiVersion: v1
kind: Service
metadata:
  name: avatar-service
  namespace: empatia
  labels:
    app: avatar-service
spec:
  type: ClusterIP
  ports:
    - port: 8002
      targetPort: 8002
      name: http
  selector:
    app: avatar-service
