apiVersion: v1
kind: ServiceAccount
metadata:
  name: empatia-app
  namespace: empatia
  annotations:
    # Workload Identity: vincula este ServiceAccount ao GCP Service Account
    iam.gke.io/gcp-service-account: empatia-app@PROJECT_ID.iam.gserviceaccount.com
