apiVersion: v1
kind: Service
metadata:
  name: voice-service
  namespace: empatia
  labels:
    app: voice-service
spec:
  type: ClusterIP
  ports:
    - port: 8004
      targetPort: 8004
      name: http
  selector:
    app: voice-service
