apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: empatia
  labels:
    app: mongodb
spec:
  # ClusterIP — acessível apenas internamente no cluster
  type: ClusterIP
  clusterIP: None  # Headless service para StatefulSet
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  selector:
    app: mongodb
